import { Group, Loan, Member, Pool, Share, Transaction } from '../types';

export const currentUser: Member = {
  id: '1',
  name: 'Sibusiso Mashita',
  sharesOwned: 24,
  totalCommitment: 120000,
  paidSoFar: 96000,
  remaining: 24000,
  role: 'member',
};

export const group: Group = {
  id: 'g1',
  name: 'Vault Vibes',
  totalMembers: 12,
  yearEnd: '2026-12-31',
};

export const shares: Share = {
  id: 's1',
  pricePerShare: 5000,
  totalShares: 240,
  sharesSold: 216,
  sharesAvailable: 24,
};

export const pool: Pool = {
  totalBalance: 1248000,
  capitalCommitted: 1200000,
  capitalReceived: 1080000,
  liquidityAvailable: 748000,
  activeLoans: 3,
  totalLoansValue: 500000,
  perShareValue: 5778,
};

export const members: Member[] = [
  currentUser,
  {
    id: '2',
    name: 'Sifumene Msane',
    sharesOwned: 20,
    totalCommitment: 100000,
    paidSoFar: 100000,
    remaining: 0,
    role: 'treasurer',
  },
  {
    id: '3',
    name: 'Mduduzi Ndlovu',
    sharesOwned: 18,
    totalCommitment: 90000,
    paidSoFar: 72000,
    remaining: 18000,
    role: 'member',
  },
  {
    id: '4',
    name: 'Siboniso Mqu',
    sharesOwned: 22,
    totalCommitment: 110000,
    paidSoFar: 110000,
    remaining: 0,
    role: 'member',
  },
  {
    id: '5',
    name: 'Thabsile  ',
    sharesOwned: 16,
    totalCommitment: 80000,
    paidSoFar: 64000,
    remaining: 16000,
    role: 'member',
  },
  {
    id: '6',
    name: 'Muzi Hlengwa',
    sharesOwned: 19,
    totalCommitment: 95000,
    paidSoFar: 95000,
    remaining: 0,
    role: 'member',
  },
  {
    id: '7',
    name: 'Phumlani',
    sharesOwned: 21,
    totalCommitment: 105000,
    paidSoFar: 84000,
    remaining: 21000,
    role: 'member',
  },
  {
    id: '8',
    name: 'Thina',
    sharesOwned: 17,
    totalCommitment: 85000,
    paidSoFar: 85000,
    remaining: 0,
    role: 'member',
  },
  {
    id: '9',
    name: 'Yolisa',
    sharesOwned: 20,
    totalCommitment: 100000,
    paidSoFar: 80000,
    remaining: 20000,
    role: 'member',
  },
  {
    id: '10',
    name: 'Nomsa Buthelezi',
    sharesOwned: 15,
    totalCommitment: 75000,
    paidSoFar: 60000,
    remaining: 15000,
    role: 'member',
  },
  {
    id: '11',
    name: 'Lerato Molefe',
    sharesOwned: 14,
    totalCommitment: 70000,
    paidSoFar: 70000,
    remaining: 0,
    role: 'member',
  },
  {
    id: '12',
    name: 'Mpho Radebe',
    sharesOwned: 10,
    totalCommitment: 50000,
    paidSoFar: 40000,
    remaining: 10000,
    role: 'member',
  },
];

export const transactions: Transaction[] = [
  {
    id: 't1',
    memberId: '1',
    memberName: 'Sibusiso Mashita',
    type: 'contribution',
    amount: 4000,
    date: '2026-02-10',
    status: 'completed',
    description: 'Monthly contribution',
  },
  {
    id: 't2',
    memberId: '2',
    memberName: 'Sifumene Msane',
    type: 'contribution',
    amount: 5000,
    date: '2026-02-09',
    status: 'completed',
    description: 'Monthly contribution',
  },
  {
    id: 't3',
    memberId: '5',
    memberName: 'Thabsile',
    type: 'loan',
    amount: 200000,
    date: '2026-02-08',
    status: 'approved',
    description: 'Business expansion loan',
  },
  {
    id: 't4',
    memberId: '3',
    memberName: 'Siboniso Mqu',
    type: 'contribution',
    amount: 3000,
    date: '2026-02-07',
    status: 'completed',
    description: 'Monthly contribution',
  },
  {
    id: 't5',
    memberId: '8',
    memberName: 'Mduduzi Ndlovu',
    type: 'contribution',
    amount: 5000,
    date: '2026-02-05',
    status: 'completed',
    description: 'Monthly contribution',
  },
  {
    id: 't6',
    memberId: '1',
    memberName: 'Thabo Mokoena',
    type: 'contribution',
    amount: 4000,
    date: '2026-01-10',
    status: 'completed',
    description: 'Monthly contribution',
  },
  {
    id: 't7',
    memberId: '4',
    memberName: 'Zanele Ndlovu',
    type: 'purchase',
    amount: 10000,
    shares: 2,
    date: '2026-01-15',
    status: 'completed',
    description: 'Additional shares purchase',
  },
  {
    id: 't8',
    memberId: '7',
    memberName: 'Bongani Zulu',
    type: 'contribution',
    amount: 4200,
    date: '2026-01-12',
    status: 'completed',
    description: 'Monthly contribution',
  },
  {
    id: 't9',
    memberId: '6',
    memberName: 'Thandiwe Mthembu',
    type: 'loan',
    amount: 150000,
    date: '2025-12-20',
    status: 'approved',
    description: 'Home improvement loan',
  },
  {
    id: 't10',
    memberId: '9',
    memberName: 'Sello Motaung',
    type: 'contribution',
    amount: 4000,
    date: '2025-12-15',
    status: 'completed',
    description: 'Monthly contribution',
  },
];

export const loans: Loan[] = [
  {
    id: 'l1',
    memberId: '5',
    memberName: 'Mandla Sibeko',
    amount: 200000,
    amountRepaid: 0,
    interestRate: 8,
    monthlyPayment: 18364,
    monthsRemaining: 12,
    status: 'approved',
    dateIssued: '2026-02-08',
  },
  {
    id: 'l2',
    memberId: '6',
    memberName: 'Thandiwe Mthembu',
    amount: 150000,
    amountRepaid: 36000,
    interestRate: 8,
    monthlyPayment: 13773,
    monthsRemaining: 9,
    status: 'active',
    dateIssued: '2025-12-20',
  },
  {
    id: 'l3',
    memberId: '3',
    memberName: 'Sipho Dlamini',
    amount: 150000,
    amountRepaid: 75000,
    interestRate: 8,
    monthlyPayment: 13773,
    monthsRemaining: 6,
    status: 'active',
    dateIssued: '2025-08-01',
  },
];
